// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: "enable",
  aws_bots: "enable",
  aws_bots_config: [
    {
      name: "avotMOBILEHUB",
      alias: "$LATEST",
      description: "Bot to make reservations for a visit to a city.",
      "bot-template": "bot-trips",
      "commands-help": [
        "Book a car",
        "Reserve a car",
        "Make a car reservation",
        "Book a hotel",
        "Reserve a room",
        "I want to make a hotel reservation"
      ],
      region: "us-east-1"
    }
  ],
  aws_cognito_identity_pool_id:
    "us-west-2:c005d01c-8cc3-4791-ac6d-b8f189984676",
  aws_cognito_region: "us-west-2",
  aws_content_delivery: "enable",
  aws_content_delivery_bucket: "avomarket-hosting-mobilehub-1283872958",
  aws_content_delivery_bucket_region: "us-west-1",
  aws_content_delivery_cloudfront: "enable",
  aws_content_delivery_cloudfront_domain: "d3fh097wp56s1n.cloudfront.net",
  aws_mobile_analytics_app_id: "a120d783bd8e4c2982ad6f620fba5da3",
  aws_mobile_analytics_app_region: "us-east-1",
  aws_project_id: "08458b5a-54d7-460b-b81a-54626242c496",
  aws_project_name: "avo_market-2019-02-02-21-58-53",
  aws_project_region: "us-west-1",
  aws_resource_name_prefix: "avomarket-mobilehub-1283872958",
  aws_sign_in_enabled: "enable",
  aws_user_pools: "enable",
  aws_user_pools_id: "us-west-2_6iRjtspKM",
  aws_user_pools_mfa_type: "ON",
  aws_user_pools_web_client_id: "4f3jrnui2crh9d22bdn321ml9f"
};

export default awsmobile;
